---
version: "3.7"

### JDownloader viene servito dalla rete VPN del container di NORDPVN,
### quindi non necessita della configurazione della rete e delle porte.
### È sufficiente aprire la porta 5800 sul container della VPN
### e accedere su protonvpn:5800

# SERVICES
services:
  jdownloader:
    container_name: ${CONTAINER_NAME}
    image: ${IMG_LINK}:${IMG_VERSION:-latest}
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - SECURE_CONNECTION=1
      - DISPLAY_WIDTH=${DISPLAY_WIDTH:-1280}
      - DISPLAY_HEIGHT=${DISPLAY_HEIGHT:-768}
    volumes:
      - "./conf/config:/config:rw"
      - "${DIR_DOWNLOAD_FOLDER}/_jdownloader:/output:rw"
    labels:
      - "diun.enable=true"
    #network_mode: container:nordvpn
    network_mode: container:protonvpn
    profiles:
      - ${PROFILE}
    restart: unless-stopped