---
version: "3.7"

# NETWORKS
networks:
  npm_proxy:
    external:
      name: npm_proxy

# SERVICES
services:
  nordvpn:
    container_name: ${CONTAINER_NAME}
    image: ${IMG_LINK}:${IMG_VERSION:-latest}
    cap_add:
      - net_admin
    devices:
      - /dev/net/tun
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - USER=${NORDVPN_USERNAME}
      - PASS=${NORDVPN_PASSWORD}
      - COUNTRY=${COUNTRY:-Spain;Hong Kong;IE;131}
      - GROUP=${GROUP:-Standard VPN servers}
      - RANDOM_TOP=${RANDOM_TOP:-10}
      - RECREATE_VPN_CRON=${RECREATE_VPN_CRON:-5 */3 * * *}
      - NETWORK=${NETWORK:-192.166.1.0/24}
      - OPENVPN_OPTS=${OPENVPN_OPTS:---mute-replay-warnings}
    volumes:
      - './conf:/data'
    labels:
      - "diun.enable=true"
    ports:
      - target: ${PORT_INT_NORDVPN_HTTP:-80}
        #published: ${PORT_PUB}
        protocol: tcp
      - target: ${PORT_INT_NORDVPN_HTTPS:-443}
        #published: ${PORT_PUB}
      - target: ${PORT_INT_JDOWNLOADER:-5800}
        #published: ${PORT_PUB}
        protocol: tcp
    networks:
      npm_proxy:
        ipv4_address: ${IP}
    profiles:
      - ${PROFILE}
    restart: unless-stopped