---
version: "3.7"

# NETWORKS
networks:
  npm_proxy:
    external:
      name: npm_proxy

# SERVICES
services:
  portainer:
    container_name: ${CONTAINER_NAME}
    image: ${IMG_LINK}:${IMG_VERSION:-latest}
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - DOCKER_HOST=tcp://socket_proxy:2375
    volumes:
      - './conf:/data'
    labels:
      - "diun.enable=true"
    ports:
      - target: ${PORT_INT_EDGEAGENT}
        #published: ${PORT_PUB_EDGEAGENT}
        protocol: tcp
      - target: ${PORT_INT_HTTP}
        #published: ${PORT_PUB_HTTP}
        protocol: tcp
      - target: ${PORT_INT_HTTPS}
        #published: ${PORT_PUB_HTTPS}
        protocol: tcp
    networks:
      npm_proxy:
        ipv4_address: ${IP}
    profiles:
      - ${PROFILE}
    restart: unless-stopped