---
version: "3.7"

# NETWORKS
networks:
  npm_proxy:
    external:
      name: npm_proxy

# SERVICES
services:
  radarr:
    container_name: ${CONTAINER_NAME}
    image: ${IMG_LINK}:${IMG_VERSION:-latest}
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ./conf:/config # Configurazioni
      - ${DIR_DOWNLOAD_FOLDER}:/downloads # Downloads
      - ${DIR_MEDIA}/movies:/movies # Libreria 1
      - ${DIR_MEDIA}/kids:/kids # Libreria 2
      - ${DIR_MEDIA}/gigs:/gigs # Libreria 3
    labels:
      - "diun.enable=true"
    ports:
      - target: ${PORT_INT}
        #published: ${PORT_PUB}
        protocol: tcp
    networks:
      npm_proxy:
        ipv4_address: ${IP}
    profiles:
      - ${PROFILE}
    restart: unless-stopped