---
version: "3.7"

# NETWORKS
networks:
  npm_proxy:
    external:
      name: npm_proxy

secrets:
  AUTH_JWT_SECRET:
    file: ./secrets/AUTH_JWT_SECRET.txt
  AUTH_SESSION_SECRET:
    file: ./secrets/AUTH_SESSION_SECRET.txt
  AUTH_NOTIFIER_SMTP_PASSWORD:
    file: ./secrets/AUTH_NOTIFIER_SMTP_PASSWORD.txt
  AUTH_STORAGE_ENCRYPTION_KEY:
    file: ./secrets/AUTH_STORAGE_ENCRYPTION_KEY.txt
  AUTH_STORAGE_MYSQL_PASSWORD:
    file: ./secrets/AUTH_STORAGE_MYSQL_PASSWORD.txt
  AUTH_AUTHENTICATION_BACKEND_LDAP_PASSWORD:
    file: ./secrets/AUTH_AUTHENTICATION_BACKEND_LDAP_PASSWORD.txt

# SERVICES
services:
  authelia:
    container_name: ${CONTAINER_NAME}
    image: ${IMG_LINK}:${IMG_VERSION:-latest}
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - AUTHELIA_JWT_SECRET_FILE=/run/secrets/AUTH_JWT_SECRET
      - AUTHELIA_SESSION_SECRET_FILE=/run/secrets/AUTH_SESSION_SECRET
      - AUTHELIA_NOTIFIER_SMTP_PASSWORD_FILE=/run/secrets/AUTH_NOTIFIER_SMTP_PASSWORD
      - AUTHELIA_STORAGE_ENCRYPTION_KEY_FILE=/run/secrets/AUTH_STORAGE_ENCRYPTION_KEY
      - AUTHELIA_STORAGE_MYSQL_PASSWORD_FILE=/run/secrets/AUTH_STORAGE_MYSQL_PASSWORD
      #- AUTHELIA_AUTHENTICATION_BACKEND_LDAP_PASSWORD_FILE=/run/secrets/AUTH_AUTHENTICATION_BACKEND_LDAP_PASSWORD
    secrets:
      - AUTH_JWT_SECRET
      - AUTH_SESSION_SECRET
      - AUTH_NOTIFIER_SMTP_PASSWORD
      - AUTH_STORAGE_ENCRYPTION_KEY
      - AUTH_STORAGE_MYSQL_PASSWORD
      - AUTH_AUTHENTICATION_BACKEND_LDAP_PASSWORD
    volumes:
      - './conf/config:/config'
      - './secrets:/config/secrets'
    labels:
      - "diun.enable=true"
      # Flame
      - flame.type=app
      - flame.name=${CONTAINER_NAME}
      - flame.url=https://${CONTAINER_NAME}.${DOMAIN_NAME}
      - flame.icon=${CONTAINER_NAME}.svg
    ports:
      - target: ${PORT_INT}
        #published: ${PORT_PUB}
        protocol: tcp
    networks:
      npm_proxy:
        ipv4_address: ${IP}
    profiles:
      - ${PROFILE}
    restart: unless-stopped