---
version: "3.7"

# NETWORKS
networks:
  npm_proxy:
    external:
      name: npm_proxy

# SERVICES
services:
  glances:
    container_name: ${CONTAINER_NAME}
    image: ${IMG_LINK}:${IMG_VERSION:-latest}
    environment:
      GLANCES_OPT: "-C /glances/conf/glances.conf -w"
      PUID: ${PUID}
      PGID: ${PGID}
      TZ: ${TZ}
      DOCKER_HOST: tcp://socket_proxy:2375
    #pid: host
    volumes:
      - './conf/glances.conf:/glances/conf/glances.conf'
    labels:
      # Diun
      - "diun.enable=true"
    ports:
      - target: ${PORT_INT_HTTP}
        #published: ${PORT_PUB_HTTP}
        protocol: tcp
      - target: ${PORT_INT_HTTPS}
        #published: ${PORT_PUB_HTTPS}
        protocol: tcp
    networks:
      npm_proxy:
        ipv4_address: ${IP}
    profiles:
      - ${PROFILE}
    restart: unless-stopped