---
version: "3.7"

# NETWORKS
networks:
  npm_proxy:
    external:
      name: npm_proxy

# SERVICES
services:
  snipeit:
    container_name: ${CONTAINER_NAME}
    image: ${IMG_LINK}:${IMG_VERSION:-latest}
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      # DATABASE
      - MYSQL_PORT_3306_TCP_ADDR=${MYSQL_PORT_3306_TCP_ADDR}
      - MYSQL_PORT_3306_TCP_PORT=${MYSQL_PORT_3306_TCP_PORT}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      # APP
      - APP_URL=${APP_URL}
      - APP_ENV=${APP_ENV}
      - APP_DEBUG=${APP_DEBUG}
      - APP_LOCALE=${APP_LOCALE}
      - APP_TRUSTED_PROXIES=**
      # MAIL
      - MAIL_PORT_587_TCP_ADDR=${MAIL_PORT_587_TCP_ADDR}
      - MAIL_PORT_587_TCP_PORT=${MAIL_PORT_587_TCP_PORT}
      - MAIL_ENV_FROM_ADDR=${MAIL_ENV_FROM_ADDR}
      - MAIL_ENV_FROM_NAME=${MAIL_ENV_FROM_NAME}
      - MAIL_ENV_ENCRYPTION=${MAIL_ENV_ENCRYPTION}
      - MAIL_ENV_USERNAME=${MAIL_ENV_USERNAME}
      - MAIL_ENV_PASSWORD=${MAIL_ENV_PASSWORD}
    volumes:
      - './conf/config:/config'
    labels:
      - "diun.enable=true"
    ports:
      # - target: ${PORT_INT_HTTP}
      #   #published: ${PORT_PUB_HTTP}
      #   protocol: tcp
      - target: ${PORT_INT_HTTPS}
        #published: ${PORT_PUB_HTTPS}
        protocol: tcp
    networks:
      npm_proxy:
        ipv4_address: ${IP}
    profiles:
      - ${PROFILE}
    restart: unless-stopped