---
version: "3.7"

# NETWORKS
networks:
  npm_proxy:
    external:
      name: npm_proxy

# SECRETS
secrets:
  POSTGRES_ROOT_PASSWORD:
    file: ./secrets/POSTGRES_ROOT_PASSWORD.txt

# SERVICES
services:
  postgres:
    container_name: ${CONTAINER_NAME}
    image: ${IMG_LINK}:${IMG_VERSION:-latest}
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - POSTGRES_USER=${DB_USER:-postgres}
      - POSTGRES_PASSWORD_FILE=/run/secrets/POSTGRES_ROOT_PASSWORD
      - POSTGRES_MULTIPLE_DATABASES=${POSTGRES_MULTIPLE_DATABASES}
    secrets:
      - POSTGRES_ROOT_PASSWORD
    volumes:
      - './conf/data:/var/lib/postgresql/data'
      - './conf/postgresql_multiple_databases:/docker-entrypoint-initdb.d'
    labels:
      - "diun.enable=true"
    ports:
      - target: ${PORT_INT}
        #published: ${PORT_PUB}
        protocol: tcp
    networks:
      npm_proxy:
        ipv4_address: ${IP}
    profiles:
      - ${PROFILE}
    restart: unless-stopped